import{a as p,S as w,i as d}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const m="https://pixabay.com/api/",u="42435331-5518aafb74583ec5494003d9b",g=15;class M{constructor(){}async getImages(o){const a={key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:g},n=`${m}`;return p.get(n,{params:a}).then(r=>r.data)}async getMoreImages(o,a){a++;const n={key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:g},r=`${m}`;return p.get(r,{params:n}).then(s=>s.data)}}const E={captionsData:"alt",captionDelay:250};let h=new w(".gallery-link",E);function v(t,o){const a=t.hits.map(n=>y(n)).join("");o.innerHTML=a,h.refresh()}function P(t,o){const a=t.hits.map(n=>y(n)).join("");o.insertAdjacentHTML("beforeend",a),h.refresh()}function I(){d.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),e.hideLoader()}function y(t){return`
        <div class="photo-container">
            <a class="gallery-link" href="${t.largeImageURL}" data-lightbox="image">
                <img src="${t.webformatURL}" alt="${t.tags}" class="photo" />
            </a>
            <div class="photo-body">
                <p class="photo-name"> <span>Likes</span> <span>${t.likes}</span> </p>
                <p class="photo-name"> <span>Views</span> <span>${t.views}</span> </p>
                <p class="photo-name"> <span>Comments</span> <span>${t.comments}</span> </p>
                <p class="photo-name"> <span>Downloads</span> <span>${t.downloads}</span> </p>
            </div>
        </div>
    `}const i={formEl:document.querySelector(".js-search-form"),imgEl:document.querySelector(".js-image-container"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".loadmore-btn")};let l=1,L="";function q(){i.loader.classList.remove("hidden")}function f(){i.loader.classList.add("hidden")}i.formEl.addEventListener("submit",S);i.btnLoadMore.addEventListener("click",$);const b=new M;async function S(t){t.preventDefault(),q();const o=t.target.elements.text.value.trim();if(L=o,l=1,!o){f(),d.warning({position:"topRight",message:"Please enter a search query."}),i.btnLoadMore.style.display="none";return}try{const a=await b.getImages(o);if(v(a,i.imgEl),a.hits.length===0)throw new Error("No images found");i.btnLoadMore.style.display="block"}catch{I()}finally{f()}}async function $(){try{const t=await b.getMoreImages(L,l);P(t,i.imgEl),l++,t.hits.length<15&&(i.btnLoadMore.style.display="none",d.show({title:"",message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"}))}catch{i.btnLoadMore.style.display="block"}}
//# sourceMappingURL=commonHelpers.js.map
